// ---------------------------------------------------------------------------
// HairIQ — Product library (spec sections 6, 7, 8, 10)
//
// Every product from the spec lives here. Fields:
//   tier         "drugstore" | "luxury" | null (tools/brand-agnostic)
//   crueltyFree  true → appears in the Cruelty-Free tab + gets the green badge
//   cfNote       certification detail shown in the Cruelty-Free tab
//   cfOnly       Section 10 additions — shown ONLY in the Cruelty-Free tab so
//                they don’t dilute the curated Affordable/Luxury lists
//   universal    tools (brushes, pillowcases…) — shown in every tab
//   categories   which routine steps can pick this product
//   tags         "new" → yellow badge
//
// ⚠️ Ethics note (spec §7): cruelty-free status can change with company
// ownership or regional laws. Verify current certification via Leaping Bunny
// or PETA's Beauty Without Bunnies list before finalizing these picks.
// ---------------------------------------------------------------------------

export const TIER_KEYS = ["drugstore", "luxury", "crueltyFree"];

// NOTE: the internal tier key stays "drugstore" for data stability, but the
// user-facing label is "Affordable" (spec §8.10 rename — price point matters
// more than physical retail location).
export const TIER_META = {
  drugstore: { label: "Affordable", emoji: "💸", blurb: "Budget-friendly picks that pull their weight." },
  luxury: { label: "Luxury", emoji: "✨", blurb: "Treat-yourself picks worth the splurge." },
  crueltyFree: { label: "Cruelty-Free", emoji: "🐰", blurb: "Certified or independently tracked cruelty-free brands — across every price point." },
};

export const PRODUCTS = [
  // ---- 6.1 / 8.1 — Pre-poo oils --------------------------------------------
  {
    id: "ogx-coconut-penetrating-oil",
    brand: "OGX",
    name: "Coconut Miracle Oil Penetrating Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["pre-poo", "sealer-oil", "between-wash-oil"],
    blurb: "The original, more intense treatment — coconut oil that actually penetrates the hair shaft instead of sitting on top.",
  },
  {
    id: "ogx-coconut-weightless-oil",
    brand: "OGX",
    name: "Coconut Oil Weightless Hydrating Oil Mist",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["pre-poo", "sealer-oil", "between-wash-oil"],
    blurb: "The lighter spray version — good for finer hair or pre-poo first-timers.",
  },
  {
    id: "ogx-argan-penetrating-oil",
    brand: "OGX",
    name: "Argan Oil of Morocco Penetrating Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["pre-poo", "sealer-oil", "between-wash-oil"],
    blurb: "Lighter, surface-smoothing alternative if coconut oil feels too heavy — great for shine.",
  },

  // ---- 8.2 — Clarifying shampoo --------------------------------------------
  {
    id: "loreal-everpure-clarify",
    brand: "L'Oréal",
    name: "EverPure Sulfate-Free Clarifying Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["clarifying-shampoo", "sulfate-free"],
    blurb: "Weekly reset wash that's still sulfate-free and color-safe.",
  },
  {
    id: "garnier-pure-clean",
    brand: "Garnier Fructis",
    name: "Pure Clean Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["clarifying-shampoo"],
    blurb: "Simple, cheap buildup-buster.",
  },
  {
    id: "dove-scalp-clarifying",
    brand: "Dove",
    name: "Scalp+Hair Therapy Clarifying Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["clarifying-shampoo"],
    blurb: "Scalp-focused clarifying wash.",
  },
  {
    id: "pantene-volume-body",
    brand: "Pantene",
    name: "Pro-V Volume & Body Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["clarifying-shampoo"],
    blurb: "A standout: cheap, lathers beautifully, and clarifies while adding lift — great for fine hair.",
  },
  {
    id: "loreal-metal-detox",
    brand: "L'Oréal",
    name: "Metal Detox Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["clarifying-shampoo", "chelating"],
    blurb: "Chelating formula that pulls out mineral and metal buildup — the pick before any future color service.",
  },
  {
    id: "livingproof-clarifying-detox",
    brand: "Living Proof",
    name: "Clarifying Detox Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["clarifying-shampoo"],
    blurb: "Deep clean without stripping.",
  },
  {
    id: "k18-peptide-prep",
    brand: "K18",
    name: "Peptide Prep Detox Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Independently certified cruelty-free · vegan.",
    categories: ["clarifying-shampoo", "chelating"],
    blurb: "Clarifies and preps hair so bond treatments absorb better.",
  },
  {
    id: "ouai-detox",
    brand: "OUAI",
    name: "Detox Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["clarifying-shampoo"],
    blurb: "Apple-cider-vinegar deep clean.",
  },

  // ---- 8.2 — Non-clarifying / strengthening shampoo ------------------------
  {
    id: "garnier-hair-filler-shampoo",
    brand: "Garnier Fructis",
    name: "Hair Filler + Vitamin Cg Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "Everyday strengthening wash.",
  },
  {
    id: "nym-tough-love-shampoo",
    brand: "Not Your Mother's",
    name: "Tough Love Bonding Shampoo",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers (Ethical Elephant, Cruelty-Free Kitty); not officially certified.",
    categories: ["strengthening-shampoo"],
    blurb: "Bond-building wash at an affordable price.",
  },
  {
    id: "dove-intensive-repair-shampoo",
    brand: "Dove",
    name: "Intensive Repair Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "Gentle daily driver for damaged hair.",
  },
  {
    id: "dove-bond-strength-shampoo",
    brand: "Dove",
    name: "Bond Strength Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "Dove's bond-care line, wash step.",
  },
  {
    id: "loreal-everpure-bond-shampoo",
    brand: "L'Oréal",
    name: "EverPure Bond Repair Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo", "sulfate-free"],
    blurb: "Sulfate-free bond-strengthening wash — also a solid pick for color-treated hair.",
  },
  {
    id: "pureology-strength-cure-shampoo",
    brand: "Pureology",
    name: "Strength Cure Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["strengthening-shampoo", "sulfate-free"],
    blurb: "Salon staple for damaged, color-treated hair.",
  },
  {
    id: "amika-kure-shampoo",
    brand: "amika",
    name: "The Kure Bond Repair Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified (mostly vegan; a few formulas contain keratin, honey, or lanolin).",
    categories: ["strengthening-shampoo"],
    blurb: "Bond repair wash that smells like dessert.",
  },
  {
    id: "redken-abc-shampoo",
    brand: "Redken",
    name: "Acidic Bonding Concentrate Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "The stylist-favorite bonding wash.",
  },
  {
    id: "ogx-thick-full-shampoo",
    brand: "OGX",
    name: "Thick & Full Biotin & Collagen Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["growth-shampoo", "strengthening-shampoo"],
    blurb: "Growth-supporting wash that plumps fine or thinning hair.",
  },
  {
    id: "ogx-bond-shampoo",
    brand: "OGX",
    name: "Bond Protein Repair Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "Protein bond repair for breakage-prone hair.",
  },
  {
    id: "loreal-dream-lengths-shampoo",
    brand: "L'Oréal",
    name: "Elvive Dream Lengths Restoring Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["strengthening-shampoo"],
    blurb: "A standout affordable pick — restoring wash made for long or damaged hair.",
  },
  {
    id: "dr-groot-thickening",
    brand: "Dr. Groot",
    name: "Hair Thickening Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["growth-shampoo", "strengthening-shampoo"],
    blurb: "K-beauty thickening shampoo — about $30 at Sephora, prestige tier despite the drugstore-style branding.",
  },
  {
    id: "pureology-blonde-shampoo",
    brand: "Pureology",
    name: "Strength Cure Blonde Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["strengthening-shampoo", "sulfate-free"],
    blurb: "Violet-toning repair wash made for bleached hair — tones brassiness while it strengthens. Vegan formulation (cruelty-free status unverified — L'Oréal-owned).",
  },

  // ---- 8.2 — Medicated shampoo ----------------------------------------------
  {
    id: "neutrogena-scalp-therapy",
    brand: "Neutrogena",
    name: "Scalp Therapy Anti-Dandruff Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "Gentle pyrithione-zinc option for flaking and itch.",
  },
  {
    id: "nizoral",
    brand: "Nizoral",
    name: "Anti-Dandruff Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "The heavy hitter (ketoconazole 1%) — use it as your second wash so it actually reaches the scalp.",
  },
  {
    id: "dove-dryness-itch",
    brand: "Dove",
    name: "Dryness & Itch Relief Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "Mild option when the problem is dryness more than dandruff.",
  },
  {
    id: "cerave-anti-dandruff",
    brand: "CeraVe",
    name: "Anti-Dandruff Hydrating Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "Treats flaking without drying the scalp out — good for dry-and-flaky scalps.",
  },
  {
    id: "head-shoulders-classic",
    brand: "Head & Shoulders",
    name: "Classic Clean Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "Works great as one wash within a double-wash routine — just swap it in for the second wash; it doesn't have to replace your whole system.",
  },
  {
    id: "head-shoulders-2in1",
    brand: "Head & Shoulders",
    name: "2-in-1 (Classic Clean / Tea Tree)",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["medicated-shampoo"],
    blurb: "Used as a SHAMPOO, this is genuinely good — the Tea Tree 2-in-1 especially, for dandruff and itchy scalps. Just don't let a 2-in-1 replace your real conditioner.",
  },

  // ---- 8.3 — Bond repair treatments -----------------------------------------
  {
    id: "garnier-hair-filler-bonding",
    brand: "Garnier Fructis",
    name: "Hair Filler + Bonding Treatment",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["bond-treatment"],
    blurb: "Weekly in-shower bond builder.",
  },
  {
    id: "ogx-bond-preshampoo",
    brand: "OGX",
    name: "Bond Protein Repair Pre-Shampoo Treatment",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["bond-treatment", "pre-wash-bond"],
    blurb: "Pre-shampoo formula — apply at least 10 minutes before washing.",
  },
  {
    id: "nym-tough-love-treatment",
    brand: "Not Your Mother's",
    name: "Tough Love Intense Bonding Treatment",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers; not officially certified.",
    categories: ["bond-treatment"],
    blurb: "Intense weekly bond repair on a budget.",
  },
  {
    id: "loreal-everpure-bond-concentrate",
    brand: "L'Oréal",
    name: "EverPure Bond Repair Concentrate",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["bond-treatment"],
    blurb: "Concentrated bond serum to layer into wash day.",
  },
  {
    id: "redken-abc-treatment",
    brand: "Redken",
    name: "Acidic Bonding Concentrate Treatment",
    tier: "luxury",
    crueltyFree: false,
    categories: ["bond-treatment"],
    blurb: "Salon-grade acidic bonding care.",
  },
  {
    id: "pantene-provitamin-essence",
    brand: "Pantene",
    name: "Pro-Vitamin Essence Weightless Leave-On Treatment",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["bond-treatment"],
    blurb: "Weightless leave-on strengthener.",
  },
  {
    id: "k18-mask",
    brand: "K18",
    name: "Leave-In Molecular Repair Hair Mask",
    tier: "luxury",
    universal: true, // shown in every tab incl. Affordable — owner call (rev 6)
    crueltyFree: true,
    cfNote: "Independently certified cruelty-free · vegan.",
    categories: ["bond-treatment", "protein-treatment"],
    blurb: "Yes, it's luxury-priced — and worth it even on a budget: science-backed and never successfully duped. A little goes far (every few weeks); follow the instructions so none gets wasted.",
  },
  {
    id: "olaplex-no3",
    brand: "Olaplex",
    name: "No.3 Hair Perfector",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Brand states cruelty-free; approved by Cruelty-Free Kitty. No official Leaping Bunny/PETA certification.",
    categories: ["bond-treatment", "pre-wash-bond", "mask"],
    blurb: "The at-home bond rebuilder that started it all — 15+ minutes before shampooing.",
  },
  {
    id: "livingproof-triple-bond",
    brand: "Living Proof",
    name: "Triple Bond Complex Hair Strengthener",
    tier: "luxury",
    crueltyFree: false,
    categories: ["post-bond"],
    blurb: "Post-wash strengthener — apply to damp hair and wait 10 minutes before any other product.",
  },

  // ---- 8.4 — Gloss ------------------------------------------------------------
  {
    id: "loreal-wonder-water",
    brand: "L'Oréal",
    name: "Elvive 8 Second Wonder Water",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["gloss"],
    blurb: "8-second rinse-out lamination for instant shine.",
  },
  {
    id: "loreal-everpure-lamination",
    brand: "L'Oréal",
    name: "EverPure Glossing 5-Min Lamination Mask",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["gloss", "mask"],
    blurb: "Color-safe glossing mask.",
  },
  {
    id: "amika-flash-shine",
    brand: "amika",
    name: "Flash Instant Shine Mask",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["gloss", "mask"],
    blurb: "One-minute glass-hair gloss.",
  },
  {
    id: "loreal-glycolic-gloss",
    brand: "L'Oréal",
    name: "Elvive Glycolic Gloss 5-Min Lamination",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["gloss"],
    blurb: "Glycolic-acid gloss treatment for mirror shine.",
  },

  // ---- 8.4 — Conditioner -------------------------------------------------------
  {
    id: "garnier-hair-filler-conditioner",
    brand: "Garnier Fructis",
    name: "Hair Filler + Vitamin Cg Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Everyday strengthening conditioner.",
  },
  {
    id: "nym-tough-love-conditioner",
    brand: "Not Your Mother's",
    name: "Tough Love Bonding Conditioner",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers; not officially certified.",
    categories: ["conditioner"],
    blurb: "Bonding conditioner pair to the Tough Love wash.",
  },
  {
    id: "dove-intensive-repair-conditioner",
    brand: "Dove",
    name: "Intensive Repair Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Reliable, cheap repair conditioner.",
  },
  {
    id: "dove-bond-strength-conditioner",
    brand: "Dove",
    name: "Bond Strength Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Bond-care conditioner step.",
  },
  {
    id: "loreal-everpure-bond-conditioner",
    brand: "L'Oréal",
    name: "EverPure Bond Repair Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Sulfate-free line, bond-repair conditioner.",
  },
  {
    id: "pureology-strength-cure-conditioner",
    brand: "Pureology",
    name: "Strength Cure Conditioner",
    tier: "luxury",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Rich salon conditioner for damaged lengths.",
  },
  {
    id: "amika-kure-conditioner",
    brand: "amika",
    name: "The Kure Bond Repair Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["conditioner"],
    blurb: "Bond-repair conditioner pair to The Kure wash.",
  },
  {
    id: "redken-abc-conditioner",
    brand: "Redken",
    name: "Acidic Bonding Concentrate Conditioner",
    tier: "luxury",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Acidic pH conditioner that seals the cuticle.",
  },
  {
    id: "ogx-bond-conditioner",
    brand: "OGX",
    name: "Bond Protein Repair Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Protein bond-repair conditioner for breakage-prone hair.",
  },
  {
    id: "innersense-hydrating-conditioner",
    brand: "Innersense",
    name: "Hydrating Cream Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["conditioner"],
    blurb: "Deeply hydrating clean-beauty conditioner.",
  },
  {
    id: "loreal-dream-lengths-conditioner",
    brand: "L'Oréal",
    name: "Elvive Dream Lengths Super Detangler Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "Detangling conditioner pair to Dream Lengths — slip for days.",
  },
  {
    id: "pureology-blonde-conditioner",
    brand: "Pureology",
    name: "Strength Cure Blonde Conditioner",
    tier: "luxury",
    crueltyFree: false,
    categories: ["conditioner"],
    blurb: "The toning-repair conditioner pair for bleached hair. Vegan formulation (cruelty-free status unverified).",
  },
  {
    id: "devacurl-one-condition",
    brand: "DevaCurl",
    name: "One Condition Original",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "PETA certified. (Parent company Henkel isn't cruelty-free; DevaCurl itself is independently certified.)",
    categories: ["conditioner", "curl-styler"],
    blurb: "The classic curl conditioner — rich slip for detangling while it's in.",
  },

  // ---- 8.4 — Masks -------------------------------------------------------------
  {
    id: "cer100-protein",
    brand: "CER-100",
    name: "Collagen Ceramide Cooling Protein Treatment",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask", "protein-treatment"],
    blurb: "Cult K-beauty protein treatment for limp, damaged hair.",
  },
  {
    id: "pantene-miracle-rescue-deep",
    brand: "Pantene",
    name: "Miracle Rescue Deep Repair Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "Deep repair in a budget-friendly jar.",
  },
  {
    id: "pantene-miracle-rescue-bond-mask",
    brand: "Pantene",
    name: "Miracle Rescue Intensive Bond Repair Mask",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "Intensive weekly bond mask.",
  },
  {
    id: "ogx-bond-3min-mask",
    brand: "OGX",
    name: "Bond Protein Repair 3-Minute Treatment Mask",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask", "protein-treatment"],
    blurb: "Fast protein mask for busy wash days.",
  },
  {
    id: "dove-10in1-intensive",
    brand: "Dove",
    name: "10-in-1 Serum Mask Intensive Repair",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "Serum-mask hybrid, repair edition.",
  },
  {
    id: "dove-10in1-bond",
    brand: "Dove",
    name: "10-in-1 Serum Mask Bond Strength",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "Serum-mask hybrid, bond edition.",
  },
  {
    id: "amika-kure-mask",
    brand: "amika",
    name: "The Kure Intense Repair Mask",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["mask"],
    blurb: "Intense repair mask for very damaged hair.",
  },
  {
    id: "ogx-coconut-miracle-mask",
    brand: "OGX",
    name: "Coconut Miracle Oil Hair Mask",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "Coconut-oil deep conditioner — 15–20 minutes under a shower cap.",
  },
  {
    id: "aussie-3-minute",
    brand: "Aussie",
    name: "3 Minute Miracle",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["mask"],
    blurb: "The $4 deep conditioner that's been saving dry hair for decades.",
  },
  {
    id: "briogeo-dont-despair",
    brand: "Briogeo",
    name: "Don't Despair, Repair! Deep Conditioning Mask",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["mask"],
    blurb: "Weekly rescue mask for dry, damaged hair.",
  },

  // ---- 8.6 — Leave-in conditioner & heat protectant -----------------------------
  {
    id: "pantene-miracle-rescue-spray",
    brand: "Pantene",
    name: "Miracle Rescue 10-in-1 Multitasking Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in"],
    blurb: "Leave-in, detangler, and heat shield in one bottle.",
  },
  {
    id: "tresemme-heat-spray",
    brand: "TRESemmé",
    name: "Protecting Heat Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in", "heat-protect"],
    blurb: "No-frills heat protection.",
  },
  {
    id: "tresemme-keratin-blowout",
    brand: "TRESemmé",
    name: "Keratin Smooth Blowout Heat Protect Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in", "heat-protect"],
    blurb: "Heat shield that smooths for blowouts.",
  },
  {
    id: "nym-tough-love-leave-in",
    brand: "Not Your Mother's",
    name: "Tough Love Bonding Leave-In Protector",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers; not officially certified.",
    categories: ["leave-in", "heat-protect"],
    blurb: "Bonding leave-in with heat protection built in.",
  },
  {
    id: "ogx-bond-leave-in",
    brand: "OGX",
    name: "Bond Protein Repair Leave-In Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in"],
    blurb: "Protein leave-in for fragile lengths.",
  },
  {
    id: "loreal-everpure-2in1",
    brand: "L'Oréal",
    name: "EverPure Moisture 2-in-1 Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in"],
    blurb: "Moisture leave-in, color-safe.",
  },
  {
    id: "redken-one-united",
    brand: "Redken",
    name: "One United Multi-Benefit Spray",
    tier: "luxury",
    crueltyFree: false,
    categories: ["leave-in", "heat-protect"],
    blurb: "25 benefits in one spray — the backstage staple.",
  },
  {
    id: "pureology-color-fanatic",
    brand: "Pureology",
    name: "Color Fanatic",
    tier: "luxury",
    crueltyFree: false,
    categories: ["leave-in", "heat-protect"],
    blurb: "21-benefit leave-in, the color-treated favorite.",
  },
  {
    id: "bb-invisible-oil-primer",
    brand: "Bumble and bumble",
    name: "Hairdresser's Invisible Oil Primer",
    tier: "luxury",
    crueltyFree: false,
    categories: ["leave-in", "heat-protect", "uv-protect"],
    blurb: "Silky leave-in primer combining UV filters with heat protection up to 450°F.",
  },
  {
    id: "crown-affair-leave-in",
    brand: "Crown Affair",
    name: "The Leave-In Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Confirmed vegan + cruelty-free.",
    categories: ["leave-in"],
    blurb: "Lightweight everyday leave-in for wet or dry hair — a moisturizer first, with a natural meadowfoam-oil heat buffer as a bonus.",
  },
  {
    id: "loreal-no-haircut-cream",
    brand: "L'Oréal",
    name: "Elvive Dream Lengths No Haircut Cream",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in", "sealer-cream"],
    blurb: "Everyday leave-in cream for long or damaged hair — cuts breakage and split ends, no hot tools required.",
  },
  {
    id: "loreal-purple-10in1",
    brand: "L'Oréal",
    name: "Elvive Colour Protect Purple 10-in-1 Leave-In Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["leave-in"],
    blurb: "Purple leave-in for color-treated or blonde hair — tones brassiness while it conditions.",
  },

  // ---- 8.7 — Styling -------------------------------------------------------------
  {
    id: "tresemme-dry-texture",
    brand: "TRESemmé",
    name: "Dry Texture Finishing Hairspray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["styling"],
    blurb: "Gritty, touchable texture on the cheap.",
  },
  {
    id: "livingproof-dry-volume",
    brand: "Living Proof",
    name: "Full Dry Volume & Texture Spray",
    tier: "luxury",
    crueltyFree: false,
    categories: ["styling"],
    blurb: "Instant big-hair spray.",
  },
  {
    id: "oribe-dry-texturizing",
    brand: "Oribe",
    name: "Dry Texturizing Spray",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Oribe is cruelty-free itself; parent company Kao is not.",
    categories: ["styling"],
    blurb: "The iconic texture spray.",
  },
  {
    id: "k18-astrolift",
    brand: "K18",
    name: "AstroLift Reparative Volume Spray",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Independently certified cruelty-free · vegan.",
    categories: ["styling"],
    blurb: "Volume that also repairs.",
  },
  {
    id: "tresemme-volume-mousse",
    brand: "TRESemmé",
    name: "Amplified Volume Mousse",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["styling"],
    blurb: "Classic root-lift mousse.",
  },
  {
    id: "rco-grasp",
    brand: "R+Co",
    name: "Grasp Shaping Balm",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny certified · 100% vegan.",
    categories: ["styling"],
    blurb: "Flexible shaping balm for piecey definition.",
  },

  // ---- 8.8 — Style sealers: serum -------------------------------------------------
  {
    id: "garnier-strength-serum",
    brand: "Garnier Fructis",
    name: "Strength Repair Serum",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-serum"],
    blurb: "Light strengthening serum for ends.",
  },
  {
    id: "redken-abc-serum",
    brand: "Redken",
    name: "Acidic Bonding Concentrate 24/7 Serum",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-serum"],
    blurb: "All-day bonding serum.",
  },
  {
    id: "pureology-dream-healer",
    brand: "Pureology",
    name: "Strength Cure Dream Healer Serum",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-serum"],
    blurb: "Overnight-friendly repair serum.",
  },
  {
    id: "ogx-antifrizz-argan-serum",
    brand: "OGX",
    name: "Anti-Frizz Argan Oil Serum",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-serum", "anti-frizz"],
    blurb: "Argan serum that smooths flyaways fast.",
  },

  // ---- 8.8 — Style sealers: lotion/cream -------------------------------------------
  {
    id: "pantene-miracle-rescue-3in1",
    brand: "Pantene",
    name: "Miracle Rescue 3-in-1 Multitasking Conditioner",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-cream"],
    blurb: "Leave-in cream that seals and softens.",
  },
  {
    id: "loreal-protein-recharge",
    brand: "L'Oréal",
    name: "Elvive Total Repair 5 Protein Recharge",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-cream", "protein-treatment"],
    blurb: "Protein leave-in cream for weak lengths.",
  },
  {
    id: "loreal-blowdry-primer",
    brand: "L'Oréal",
    name: "EverPure Weightless Blow Dry Primer",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-cream", "heat-protect"],
    blurb: "Weightless cream primer for heat styling days.",
  },
  {
    id: "redken-abc-leave-in",
    brand: "Redken",
    name: "Acidic Bonding Concentrate Leave-In Treatment",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-cream"],
    blurb: "Leave-in bonding cream.",
  },
  {
    id: "bb-invisible-oil-cream",
    brand: "Bumble and bumble",
    name: "Hairdresser's Invisible Oil Long Last Styling Cream",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-cream"],
    blurb: "Silky styling cream for smooth, sealed ends.",
  },

  // ---- 8.8 — Style sealers: oil ------------------------------------------------------
  {
    id: "ogx-bond-oil-mist",
    brand: "OGX",
    name: "Bond Protein Repair Oil Mist",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-oil"],
    blurb: "Fine mist oil that won't overload fine hair.",
  },
  {
    id: "dove-intensive-repair-oil",
    brand: "Dove",
    name: "Intensive Repair Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-oil", "between-wash-oil"],
    blurb: "Budget finishing oil.",
  },
  {
    id: "dove-bond-shield-oil",
    brand: "Dove",
    name: "Bond Shield Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["sealer-oil", "between-wash-oil"],
    blurb: "Bond-protecting finishing oil.",
  },
  {
    id: "livingproof-vanishing-oil",
    brand: "Living Proof",
    name: "Vanishing Oil",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-oil"],
    blurb: "Disappears into hair — shine without grease.",
  },
  {
    id: "amika-superfruit-star",
    brand: "amika",
    name: "Superfruit Star Lightweight Styling Oil",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["sealer-oil", "between-wash-oil"],
    blurb: "Lightweight styling oil that works between washes too.",
  },
  {
    id: "bb-invisible-oil",
    brand: "Bumble and bumble",
    name: "Hairdresser's Invisible Oil",
    tier: "luxury",
    crueltyFree: false,
    categories: ["sealer-oil", "between-wash-oil"],
    blurb: "The cult finishing oil.",
  },

  // ---- 8.9 — Between-wash care ---------------------------------------------------------
  {
    id: "amika-midnight-mender",
    brand: "amika",
    name: "Midnight Mender Overnight Strength Repair Treatment",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["between-wash-oil", "night-treatment"],
    blurb: "Overnight repair treatment — wake up with softer hair.",
  },
  {
    id: "dove-bond-shield",
    brand: "Dove",
    name: "Bond Shield",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["between-wash-oil"],
    blurb: "Leave-on bond protection between washes.",
  },
  {
    id: "livingproof-phd-heat",
    brand: "Living Proof",
    name: "Perfect Hair Day Heat Styling Spray",
    tier: "luxury",
    crueltyFree: false,
    categories: ["heat-protect"],
    blurb: "Heat protection before hot tools between washes.",
  },
  {
    id: "igk-good-behavior",
    brand: "IGK",
    name: "Good Behavior Spirulina Protein Smoothing Spray",
    tier: "luxury",
    crueltyFree: false,
    categories: ["heat-protect"],
    blurb: "Smoothing blowout spray with protein.",
  },
  {
    id: "moroccanoil-perfect-defense",
    brand: "Moroccanoil",
    name: "Perfect Defense",
    tier: "luxury",
    crueltyFree: false,
    categories: ["heat-protect"],
    blurb: "Dry-mist thermal protection.",
  },
  {
    id: "oribe-gold-lust-heat",
    brand: "Oribe",
    name: "Gold Lust Dry Heat Protection Spray",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Oribe is cruelty-free itself; parent company Kao is not.",
    categories: ["heat-protect"],
    blurb: "Luxe dry heat shield.",
  },
  {
    id: "amika-perk-up-plus",
    brand: "amika",
    name: "Perk Up Plus Extended Clean Dry Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny + PETA certified.",
    categories: ["dry-shampoo"],
    blurb: "Extended-wear dry shampoo that doesn't cake.",
  },
  {
    id: "livingproof-phd-dry-shampoo",
    brand: "Living Proof",
    name: "Perfect Hair Day Advanced Clean Dry Shampoo",
    tier: "luxury",
    crueltyFree: false,
    categories: ["dry-shampoo"],
    blurb: "Actually cleans — the gold-standard dry shampoo.",
  },
  {
    id: "dove-volume-dry-shampoo",
    brand: "Dove",
    name: "Volume & Fullness Advanced Dry Shampoo",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["dry-shampoo"],
    blurb: "Budget refresh with a volume boost.",
  },
  {
    id: "nym-clean-freak",
    brand: "Not Your Mother's",
    name: "Clean Freak Refreshing Dry Shampoo",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers; not officially certified.",
    categories: ["dry-shampoo"],
    blurb: "The $8 dry shampoo classic.",
  },
  {
    id: "k18-airwash",
    brand: "K18",
    name: "AirWash Dry Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Independently certified cruelty-free · vegan.",
    categories: ["dry-shampoo"],
    blurb: "Non-aerosol mist with an odor-eliminating biotech formula — a very light touch goes a long way.",
  },

  // ---- Section 7 — Thinning / slow growth -----------------------------------------------
  {
    id: "mielle-rosemary-mint",
    brand: "Mielle",
    name: "Rosemary Mint Scalp & Strengthening Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["scalp-serum"],
    blurb: "The viral rosemary scalp oil — massage in at night, 3–4× a week.",
  },
  {
    id: "maple-holistics-biotin",
    brand: "Maple Holistics",
    name: "Biotin Hair Growth Serum",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["scalp-serum"],
    blurb: "Budget biotin scalp serum.",
  },
  {
    id: "actacre-scalp-detox",
    brand: "Act+Acre",
    name: "Cold Processed Scalp Detox",
    tier: "luxury",
    crueltyFree: false,
    categories: ["scalp-serum", "scalp-scrub"],
    blurb: "Pre-wash scalp detox oil that dissolves buildup around follicles.",
  },
  {
    id: "vegamour-gro",
    brand: "Vegamour",
    name: "GRO Hair Serum",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free and vegan brand.",
    categories: ["scalp-serum"],
    blurb: "Plant-based daily density serum.",
  },
  {
    id: "briogeo-scalp-revival",
    brand: "Briogeo",
    name: "Scalp Revival Charcoal + Coconut Oil Scrub",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["scalp-scrub"],
    blurb: "Charcoal micro-exfoliating scrub — weekly scalp reset.",
  },
  {
    id: "christophe-robin-scrub",
    brand: "Christophe Robin",
    name: "Purifying Scalp Scrub",
    tier: "luxury",
    crueltyFree: false,
    categories: ["scalp-scrub"],
    blurb: "Sea-salt purifying scrub, the luxury scalp-facial.",
  },

  // ---- Section 7 — Frizz --------------------------------------------------------------------
  {
    id: "nym-frizz-go-away",
    brand: "Not Your Mother's",
    name: "Frizz Go Away",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Widely reported cruelty-free by independent trackers; not officially certified.",
    categories: ["anti-frizz", "sealer-cream"],
    blurb: "Does what it says on the bottle.",
  },
  {
    id: "livingproof-no-frizz",
    brand: "Living Proof",
    name: "No Frizz Leave-In Conditioner",
    tier: "luxury",
    crueltyFree: false,
    categories: ["anti-frizz", "leave-in"],
    blurb: "Humidity-blocking leave-in with patented tech.",
  },
  {
    id: "rahua-frizz-free-cream",
    brand: "Rahua",
    name: "Frizz-Free Cream",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["anti-frizz", "sealer-cream"],
    blurb: "Plant-powered smoothing cream.",
  },
  {
    id: "bread-hair-oil",
    brand: "Bread Beauty Supply",
    name: "Hair Oil",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["anti-frizz", "sealer-oil", "between-wash-oil"],
    blurb: "Everyday gloss oil that calms frizz without weight.",
  },

  // ---- Section 7 — Breakage (Olaplex wash pair) ----------------------------------------------
  {
    id: "olaplex-no4",
    brand: "Olaplex",
    name: "No.4 Bond Maintenance Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Brand states cruelty-free; approved by Cruelty-Free Kitty. No official certification.",
    categories: ["strengthening-shampoo"],
    blurb: "Bond-maintenance wash.",
  },
  {
    id: "olaplex-no5",
    brand: "Olaplex",
    name: "No.5 Bond Maintenance Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Brand states cruelty-free; approved by Cruelty-Free Kitty. No official certification.",
    categories: ["conditioner"],
    blurb: "Bond-maintenance conditioner.",
  },

  // ---- Section 7 — Dandruff (cruelty-free medicated) ------------------------------------------
  {
    id: "derma-e-scalp-relief",
    brand: "Derma E",
    name: "Scalp Relief Shampoo",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["medicated-shampoo"],
    blurb: "Cruelty-free relief for flaking and itch.",
  },
  {
    id: "jason-dandruff-relief",
    brand: "JASON",
    name: "Dandruff Relief Shampoo",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["medicated-shampoo"],
    blurb: "Cruelty-free alternative to Head & Shoulders.",
  },
  {
    id: "oribe-serene-scalp",
    brand: "Oribe",
    name: "Serene Scalp Anti-Dandruff Shampoo",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Oribe is cruelty-free itself; parent company Kao is not.",
    categories: ["medicated-shampoo"],
    blurb: "Dandruff care that feels like luxury.",
  },

  // ---- Section 7 — New to curly/wavy ------------------------------------------------------------
  {
    id: "cantu-curling-cream",
    brand: "Cantu",
    name: "Coconut Curling Cream",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["curl-styler", "sealer-cream"],
    blurb: "The starter curl cream — rich definition for a few dollars.",
  },
  {
    id: "aussie-miracle-curls",
    brand: "Aussie",
    name: "Miracle Curls Air Dry Cream",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["curl-styler"],
    blurb: "Air-dry cream for soft, non-crunchy waves and curls.",
  },
  {
    id: "ouidad-climate-control",
    brand: "Ouidad",
    name: "Climate Control Gel",
    tier: "luxury",
    crueltyFree: false,
    categories: ["curl-styler"],
    blurb: "Humidity-proof curl gel from the curl-salon pioneers.",
  },
  {
    id: "innersense-curl-creme",
    brand: "Innersense",
    name: "Curl Crème",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["curl-styler"],
    blurb: "Clean-beauty curl definition.",
  },
  {
    id: "bread-curl-whip",
    brand: "Bread Beauty Supply",
    name: "Curl Whip",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["curl-styler"],
    blurb: "Whipped curl styler for soft hold.",
  },

  // ---- 6.4 — Night treatments ---------------------------------------------------------------------
  {
    id: "kerastase-8h-night",
    brand: "Kérastase",
    name: "Nutritive 8H Magic Night Serum Hydrating Treatment",
    tier: "luxury",
    crueltyFree: false,
    categories: ["night-treatment"],
    blurb: "The luxury overnight serum — follow with a lightweight hair oil.",
  },
  {
    id: "loreal-miracle-serum",
    brand: "L'Oréal",
    name: "Elvive Miracle Hair Serum",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["night-treatment", "sealer-oil"],
    blurb: "The Amazon find — known dupe for Kérastase Elixir Ultime hair oil. Use it as the light-oil layer over your night serum.",
  },
  {
    id: "dove-bond-shield-10in1",
    brand: "Dove",
    name: "Bond Shield 10-in-1 Oil",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["night-treatment", "sealer-oil", "between-wash-oil"],
    blurb: "One bottle, day and night — bond-protecting oil for daytime ends and the nightly seal.",
  },
  {
    id: "crown-affair-overnight",
    brand: "Crown Affair",
    name: "Overnight Repair Serum",
    tier: "luxury",
    crueltyFree: false,
    categories: ["night-treatment"],
    blurb: "A ~$55 luxury night option in its own right — not a Kérastase dupe; bleached or heavily processed hair usually wants more repair power than this.",
  },
  {
    id: "loreal-midnight-serum",
    brand: "L'Oréal",
    name: "Elvive Extraordinary Oil Midnight Serum",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["night-treatment"],
    blurb: "Commonly cited as the much-cheaper dupe for the Kérastase 8H night serum.",
  },

  // ---- 6.6 — UV protection ---------------------------------------------------------------------------
  {
    id: "pantene-sunkiss-glow",
    brand: "Pantene",
    name: "Sunkiss Glow UV Protection Spray",
    tier: "drugstore",
    crueltyFree: false,
    categories: ["uv-protect"],
    tags: ["new"],
    blurb: "2026 launch that targets UV, salt, and chlorine exposure specifically.",
  },
  {
    id: "jvn-uv",
    brand: "JVN",
    name: "Complete UV Protection Line",
    tier: "luxury",
    crueltyFree: true,
    cfNote: "Leaping Bunny certified.",
    categories: ["uv-protect", "leave-in"],
    blurb: "Luxury UV shield — wear it as your everyday summer leave-in, not a special-occasion spray.",
  },
  {
    id: "sunbum-heat-protector",
    brand: "Sun Bum",
    name: "Heat Protector Spray",
    tier: "drugstore",
    crueltyFree: true,
    cfNote: "Cruelty-free brand.",
    categories: ["heat-protect", "uv-protect"],
    blurb: "Beach-brand spray that shields against heat and sun.",
  },

  // ---- Section 10 — Expanded cruelty-free library (CF tab only) -----------------------------------------
  {
    id: "aveda-range",
    brand: "Aveda",
    name: "Shampoo & Conditioner (full range, incl. scalp care)",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Leaping Bunny certified · 100% vegan.",
    categories: ["strengthening-shampoo", "conditioner", "scalp-serum"],
    blurb: "Salon icon — the whole range qualifies, including scalp care.",
  },
  {
    id: "pacifica-range",
    brand: "Pacifica Beauty",
    name: "Shampoo & Conditioner ranges",
    tier: "drugstore",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["strengthening-shampoo", "conditioner"],
    blurb: "Budget-friendly — easy to find at Target.",
  },
  {
    id: "verb-range",
    brand: "Verb",
    name: "Shampoo & Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["strengthening-shampoo", "conditioner"],
    blurb: "Especially good for fine hair.",
  },
  {
    id: "curlsmith-range",
    brand: "CurlSmith",
    name: "Protein-Free Curl Range",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["curl-styler", "conditioner", "sulfate-free"],
    blurb: "Protein-free formulas built for curly hair.",
  },
  {
    id: "acure-range",
    brand: "ACURE",
    name: "Shampoo & Conditioner",
    tier: "drugstore",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Leaping Bunny + PETA certified · B Corp.",
    categories: ["strengthening-shampoo", "conditioner"],
    blurb: "Affordable, certified, and B Corp to boot.",
  },
  {
    id: "giovanni-range",
    brand: "Giovanni",
    name: "Shampoo & Conditioner",
    tier: "drugstore",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["strengthening-shampoo", "conditioner"],
    blurb: "Salon-quality formulas at grocery-store prices.",
  },
  {
    id: "ethique-bars",
    brand: "Ethique",
    name: "Solid Shampoo Bars",
    tier: "drugstore",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["strengthening-shampoo"],
    blurb: "Zero-waste shampoo bars.",
  },
  {
    id: "paul-mitchell-range",
    brand: "Paul Mitchell",
    name: "Shampoo & Conditioner",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free since 1980 · Leaping Bunny + PETA certified.",
    categories: ["strengthening-shampoo", "conditioner"],
    blurb: "The original cruelty-free salon brand.",
  },
  {
    id: "jvn-line",
    brand: "JVN",
    name: "Styling Serums & Oils",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Leaping Bunny certified.",
    categories: ["sealer-serum", "sealer-oil", "styling"],
    blurb: "Jonathan Van Ness's line — styling, serum, and oil picks.",
  },
  {
    id: "playa-ritual-oil",
    brand: "Playa",
    name: "Ritual Hair Oil",
    tier: "luxury",
    crueltyFree: true,
    cfOnly: true,
    cfNote: "Cruelty-free brand.",
    categories: ["sealer-oil", "pre-poo", "between-wash-oil"],
    blurb: "Natural coconut, apricot, and sunflower oil blend — doubles as a cruelty-free pre-poo.",
  },

  // ---- Tools (shown in every tab) --------------------------------------------------------------------------
  {
    id: "scalp-massage-brush",
    brand: "Any brand",
    name: "Wood or Bamboo Scalp Massage Brush",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-scalp"],
    blurb: "About $10 for a multi-pack on Amazon — distributes product, gently exfoliates buildup, and the stimulation may support circulation.",
  },
  {
    id: "satin-pillowcase",
    brand: "Any brand",
    name: "Satin Pillowcase + Bonnet",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-night"],
    blurb: "The budget version of the friction fix (~$10) — smooth weave, less breakage and frizz all night.",
  },
  {
    id: "silk-pillowcase",
    brand: "Any brand",
    name: "Mulberry Silk Pillowcase + Bonnet",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-night"],
    blurb: "The luxury fabric — cooler and smoother than satin, same friction science, nicer feel.",
  },
  {
    id: "microfiber-towel",
    brand: "Any brand",
    name: "Microfiber Hair Towel (or an old cotton t-shirt)",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-dry"],
    blurb: "Rough terry towels rough up the cuticle — microfiber or a t-shirt dries gently.",
  },
  {
    id: "wide-tooth-comb",
    brand: "Any brand",
    name: "Wide-Tooth Comb",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-detangle"],
    blurb: "The only thing that should detangle wet hair.",
  },
  // Brushes (spec §11.2) — lookup on hair type AND density: pure boar for
  // straight fine/normal, boar+nylon blend for straight thick, wet detangling
  // brush for any texture. Affordable-tier and cruelty-free brand picks are
  // pending exact names from Crystal — generics stay brand-agnostic.
  {
    id: "wet-detangling-brush",
    brand: "Any brand",
    name: "Wet Detangling Brush",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-brush-wet", "tool-detangle"],
    blurb: "Flexible bristles built for wet, tangled hair — works through knots without snapping curls.",
  },
  {
    id: "boar-bristle-brush",
    brand: "Any brand",
    name: "Boar Bristle Brush",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-brush-boar"],
    blurb: "Carries your scalp's natural oils down the length for shine — something a detangling brush isn't designed to do.",
  },
  {
    id: "boar-nylon-blend-brush",
    brand: "Any brand",
    name: "Boar + Nylon Blend Brush",
    tier: null,
    universal: true,
    crueltyFree: false,
    categories: ["tool-brush-blend"],
    blurb: "Distributes oils like pure boar, with nylon pins that actually get through thicker hair.",
  },
  {
    id: "mason-pearson",
    brand: "Mason Pearson",
    name: "Boar Bristle Brush",
    tier: "luxury",
    crueltyFree: false,
    categories: ["tool-brush-boar"],
    blurb: "The original, iconic boar bristle brush (~$250) — the heirloom version of this step.",
  },
  {
    id: "crown-affair-brush",
    brand: "Crown Affair",
    name: "Mini Dual-Bristle Boar Hair Brush",
    tier: "luxury",
    crueltyFree: false,
    categories: ["tool-brush-blend"],
    blurb: "Luxury boar + nylon blend for thicker strands. (The brand's leave-in line is confirmed vegan/cruelty-free; the brush line hasn't been verified.)",
  },
];

export function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

// Pool of candidate products for one tier tab.
//   drugstore   → drugstore-tier products (plus universal tools)
//   luxury      → luxury-tier products (plus universal tools)
//   crueltyFree → anything cruelty-free, any price point (plus universal tools)
export function productPool(tierKey) {
  return PRODUCTS.filter((p) => {
    if (p.universal) return true;
    if (tierKey === "crueltyFree") return p.crueltyFree === true;
    return p.tier === tierKey && !p.cfOnly;
  });
}
